config/routes.rb
Rails.application.routes.draw do
    post 'session/create', as: :log_in
    get 'session/destroy', as: :log_out

  resources :news

  resources :navs

  resources :pages

  get 'welcome/index'

   root 'welcome#index'

end

app/models/nav.rb
class Nav < ActiveRecord::Base
	belongs_to :parent, class_name: "Nav"
	belongs_to :page
	
	has_many :children, class_name: "Nav", foreign_key: :parent_id
end

app/models/news.rb
class News < ActiveRecord::Base
	belongs_to :page
	belongs_to :photo
	
	def user
	    User.find(creator_dn)
    end
end

app/models/page.rb
class Page < ActiveRecord::Base
	extend FriendlyId

	friendly_id :name, use: :slugged
	has_paper_trail
end

app/models/user.rb
class User < ActiveLdap::Base
	ldap_mapping dn_attribute: "mail",
				 prefix: "",
				 classes: ["inetOrgPerson"]

	def User.authenticate(mail, password)
		user = find(:first, filter: {mail: mail})
		user.bind(password)
		user
	rescue ActiveLdap::EntryNotFound, ActiveLdap::AuthenticationError, ActiveLdap::LdapError::UnwillingToPerform, NoMethodError
		nil
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
    before_action :get_top_navbar
    def get_top_navbar
        @navbar_items = Nav.where(parent_id: nil).order(:sort_index)
    end

    def current_user
        @current_user ||= (session[:udn] ? User.find(session[:udn]) : nil)
    end

    def current_role? r
        if current_user
            [current_user.employeeType].flatten.include? r
        else
            false
        end
    end

    helper_method :current_user, :current_role?
end

app/controllers/navs_controller.rb
class NavsController < ApplicationController
  before_action :set_nav, only: [:show, :edit, :update, :destroy]

  # GET /navs
  # GET /navs.json
  def index
    @navs = Nav.all
  end

  # GET /navs/1
  # GET /navs/1.json
  def show
  end

  # GET /navs/new
  def new
    @nav = Nav.new
  end

  # GET /navs/1/edit
  def edit
  end

  # POST /navs
  # POST /navs.json
  def create
    @nav = Nav.new(nav_params)

    respond_to do |format|
      if @nav.save
        format.html { redirect_to @nav, notice: 'Nav was successfully created.' }
        format.json { render :show, status: :created, location: @nav }
      else
        format.html { render :new }
        format.json { render json: @nav.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /navs/1
  # PATCH/PUT /navs/1.json
  def update
    respond_to do |format|
      if @nav.update(nav_params)
        format.html { redirect_to @nav, notice: 'Nav was successfully updated.' }
        format.json { render :show, status: :ok, location: @nav }
      else
        format.html { render :edit }
        format.json { render json: @nav.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /navs/1
  # DELETE /navs/1.json
  def destroy
    @nav.destroy
    respond_to do |format|
      format.html { redirect_to navs_url, notice: 'Nav was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nav
      @nav = Nav.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nav_params
      params.require(:nav).permit(:name, :sort_index, :link, :parent_id)
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)
    @news.creator_dn = current_user.dn.to_s
    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:name, :description, :link, :creator_dn)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:name, :content)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
      if u = User.authenticate(params[:email], params[:password])
          session[:udn] = u.dn.to_s
          flash[:notice] = "Welcome, #{u.cn}"
      else
          flash[:error] = "Login failed."
      end
      redirect_to root_path
  end

  def destroy
      session.delete :udn
      redirect_to root_path
  end

  def reset
      if current_user
          if params[:password] == params[:confirm]
              current_user.userPassword = params[:password]
              current_user.save
          else
              flash[:error] = "Confirmation didn't match password."
          end
      else
          flash[:error] = "You can't do that."
      end
      redirect_to me_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/navs_helper.rb
module NavsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<!--Custom fonts (Josefin Slab) -->
<link href='http://fonts.googleapis.com/css?family=Josefin+Slab:400,700' rel='stylesheet' type='text/css'>
<!--Custom fonts (Raleway) -->
<link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
<title>WBI 461 Website</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">


            <a class="navbar-brand" href="/"><img class="navbar-brand" src="http://assets.boilerinvasion.org/assets/logo-b67204d087e9388f80a15cfd3ddcd035.png"></a>

        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
            </ul>
            <ul class="nav navbar-nav navbar-left">
                <% @navbar_items.each do |x_nav| %>
                    <% if x_nav.children.count > 0 %>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= x_nav.name %><span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <% x_nav.children.each do |sane| %>
                                <li><%= link_to sane.name, sane.link %> </li>
                            <% end %>
                        </ul>
                    </li>
                <% else %>
                    <li><%= link_to x_nav.name, x_nav.link %> </li>
                <% end %>
                <% end %>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <% if current_user %>
                    <li><%= link_to "Log Out #{current_user.cn}", log_out_path %></li>
                <% else %>
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Login</a>
                    <ul class="dropdown-menu" role="menu">
                        <%= form_tag log_in_path do %>
							<div class="form-group login-group">
								<li><%= text_field_tag :email, nil, class: 'form-control' %></li>
								<li><%= password_field_tag :password, nil, class: 'form-control' %></li>
								<li><%= submit_tag "Log In", class: 'btn' %>
							</div>
                        <% end %>
                    </ul>
                    </li>
                <% end %>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="container-fluid main-container">
    <div class="row">
        <div class="col-md-12">
            <%= yield %>
        </div>
    </div>
</div>
</body>
</html>

app/views/navs/_form.html.erb
<%= form_for(@nav) do |f| %>
  <% if @nav.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nav.errors.count, "error") %> prohibited this nav from being saved:</h2>

      <ul>
      <% @nav.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :sort_index %><br>
    <%= f.number_field :sort_index %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br>
    <%= f.number_field :parent_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/navs/edit.html.erb
<h1>Editing Nav</h1>

<%= render 'form' %>

<%= link_to 'Show', @nav %> |
<%= link_to 'Back', navs_path %>

app/views/navs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Navs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Sort index</th>
      <th>Link</th>
      <th>Parent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @navs.each do |nav| %>
      <tr>
        <td><%= nav.name %></td>
        <td><%= nav.sort_index %></td>
        <td><%= nav.link %></td>
        <td><%= nav.parent_id %></td>
        <td><%= link_to 'Show', nav %></td>
        <td><%= link_to 'Edit', edit_nav_path(nav) %></td>
        <td><%= link_to 'Destroy', nav, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nav', new_nav_path %>

app/views/navs/new.html.erb
<h1>New Nav</h1>

<%= render 'form' %>

<%= link_to 'Back', navs_path %>

app/views/navs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @nav.name %>
</p>

<p>
  <strong>Sort index:</strong>
  <%= @nav.sort_index %>
</p>

<p>
  <strong>Link:</strong>
  <%= @nav.link %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @nav.parent_id %>
</p>

<%= link_to 'Edit', edit_nav_path(@nav) %> |
<%= link_to 'Back', navs_path %>

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<h1>News Items</h1>

<br>
<div class = "row">
<% @news.each do |news| %>
<div class="col-md-4 panel panel-inverse"><h3><%= link_to news.name , news%></h3>
<%= news.created_at %>
<%= news.user.cn %></div>
<% end %>
</div>
<%= link_to 'New News', new_news_path, class: "btn btn-primary" %>

app/views/news/new.html.erb
<h1>New News</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @news.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @news.description %>
</p>

<p>
  <strong>Link:</strong>
  <%= @news.link %>
</p>

<p>
  <strong>Creator dn:</strong>
  <%= @news.creator_dn %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>

<div class="container">
<% @pages.each_slice(3) do |group| %>
<div class="row">
<% group.each do |page| %>
		<div class="col-md-3">
            <div class="panel panel-inverse">
  	        <div class="panel-heading"><h3><%= link_to page.name, page %></h3></div>
  				<div class="panel-body"><%= page.content %>
  				</div>
			    </div>
		</div>
		<% end %>
</div>
<% end %>
</div>
<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

 <h2><%= @page.name %></h2>
 <br/>
 <p>
  <%= @page.content %>
 </p>
 <br/>
 <br/>
 <p>
 <%= link_to 'Edit', edit_page_path(@page) %> |
 <%= link_to 'Back', pages_path %>
 </p>

app/views/welcome/index.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
		<!-- Wrapper for slides -->
		<div class="carousel-inner" role="listbox">
			<div class="item active">
				<div class="top-image" style="background-image: url(<%= asset_path "1.jpg" %>);">
				</div>
			</div>
			<div class="item">
				<div class="top-image" style="background-image: url(<%= asset_path "2.jpg" %>);">
				</div>
			</div>
			<div class="item">
				<div class="top-image" style="background-image: url(<%= asset_path "3.jpg" %>);">
				</div>
			</div>
			<div class="item">
				<div class="top-image" style="background-image: url(<%= asset_path "4.jpg" %>);">
				</div>
			</div>
			<div class="item">
				<div class="top-image" style="background-image: url(<%= asset_path "5.jpg" %>);">
				</div>
			</div>
		</div>
		
		<!-- Controls -->
		<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
			<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
			<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div>
	<br />
	<div class="container-fluid">
		<blockquote class="about-us">
			<p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Nya!"</p>
		</blockquote>
	</div>